apiVersion: network.aws.crossplane.io/v1alpha3
kind: VPC
metadata:
  labels:
    provider: aws
  name: argo-vpc
spec:
  cidrBlock: 192.168.0.0/16
  enableDnsHostNames: true
  enableDnsSupport: true
  reclaimPolicy: Delete
