apiVersion: ec2.aws.crossplane.io/v1beta1
kind: VPC
metadata:
  name: argo-east-vpc
spec:
  forProvider:
    cidrBlock: 192.168.0.0/16
    enableDnsHostNames: true
    enableDnsSupport: true
    region: us-east-1
